import { PostCategory } from '@prisma/client'

export const POST_CATEGORIES: PostCategory[] = [
  'TECHNOLOGY',
  'EDUCATION',
  'HEALTH_AND_WELLNESS',
  'TRAVEL',
  'BUSINESS_AND_ENTREPRENEURSHIP',
  'CULTURE_AND_ENTERTAINMENT',
  'CULINARY_AND_GASTRONOMY',
  'LIFESTYLE',
  'SCIENCE_AND_INNOVATION',
  'SUSTAINABILITY_AND_ENVIRONMENT',
]
